version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pgxyyva8l8ye"
s3_prefix = "sample-lambda"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
