AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template for sample lambda.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  SampleLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: au.com.auspost.lambda.Controller::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

Outputs:
  SampleLambdaFunction:
    Description: "SampleLambda Lambda Function ARN"
    Value: !GetAtt SampleLambda.Arn
  SampleLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for SampleLambda function"
    Value: !GetAtt SampleLambda.Arn
